### PR TITLE
Convert while loop to recursive function

### PR DESCRIPTION
**Pull request by ghost**
Instead of using a while loop to GET the Google Scholar Page, use a functional approach and make it a recursive function instead.

I notice you make extensive use of purrr functions, suggesting you prefer functional code. My changes make the file a little longer but fit the paradigm more neatly, I think.

### CODE REVIEW

**Comment by cimentadaj** [comment]
Thanks @ChuckFinley ! This is a better approach, I agree. A couple of things: I just pushed some changes to delete some dependencies (such as glue). Can you adapt it? It should be minor stuff. Additionally, can you move `get_resp` outside the `get_coauthors` and just call it from within `get_coauthors`? Also feel free to add yourself as a contributor to the `DESCRIPTION` file. I'll accept the merge after that!

**Comment by ghost** [comment]
Sounds great, will do. I had fun playing around with the package - happy to
contribute!

**Comment by ghost** [comment]
Moved `get_resp` outside of `get_coauthors`, removed `glue` dependency, and added myself to the DESCRIPTION file. I didn't see any other dependencies that I need to remove, but I didn't test it thoroughly.

**Comment by cimentadaj** [comment]
Oh I meant that I already removed some dependencies. You should `git pull` from my repo and then implement the changes in the updated version. I believe that if you `pull` now everything will be up to date. I'll review this later, thanks a lot!

**Comment by ghost** [comment]
Ah, I communicated that poorly. By "any other dependencies that I need to remove" I meant function calls in the code I'm contributing. I did an upstream pull first so I got your version of the DESCRIPTION file. Should be good, but I'm new to contributing to GitHub repos so let me know if I did something wrong.

**Comment by cimentadaj** [comment]
Ah, ok cool! Thanks for the PR @ChuckFinley, merged.

**Pull request merged**
